export const Locations = {
    '1': [{
      code: 1,
      areaName: "강남구",
      areaHomepage: "http://www.gangnam.go.kr/contents/tourgangnam/1/view.do?mid=FM010406"
    }, {
      code: 2,
      areaName: "강동구",
      areaHomepage: "http://culture.gangdong.go.kr/web/portal/culture.do"
    }, {
      code: 3,
      areaName: "강북구",
      areaHomepage: "http://www.gangbuk.go.kr/tour/index.do"
    }, {
      code: 4,
      areaName: "강서구",
      areaHomepage: "http://www.gangseo.seoul.kr/site/munhwa/index.jsp"
    }, {
      code: 5,
      areaName: "관악구",
      areaHomepage: "http://www.gwanak.go.kr/site/gwanak/area/areaMain.do?cateCont=Area02"
    }, {
      code: 6,
      areaName: "광진구",
      areaHomepage: "https://www.gwangjin.go.kr/portal/main/contents.do?menuNo=200241"
    }, {
      code: 7,
      areaName: "구로구",
      areaHomepage: "http://www.guro.go.kr/culture/NR_index.do"
    }, {
      code: 8,
      areaName: "금천구",
      areaHomepage: "http://www.geumcheon.go.kr/html/001/001006005001001.html"
    }, {
      code: 9,
      areaName: "노원구",
      areaHomepage: "http://www.nowon.kr/new/tour/tour.jsp?mid=560301"
    }, {
      code: 10,
      areaName: "도봉구",
      areaHomepage: "http://tour.dobong.go.kr/"
    }, {
      code: 11,
      areaName: "동대문구",
      areaHomepage: "http://tour.ddm.go.kr/intro"
    }, {
      code: 12,
      areaName: "동작구",
      areaHomepage: "http://www.dongjak.go.kr/portal/main/contents.do?menuNo=201107"
    }, {
      code: 13,
      areaName: "마포구",
      areaHomepage: "https://www.mapo.go.kr/site/culture/home"
    }, {
      code: 14,
      areaName: "서대문구",
      areaHomepage: "http://www.sdm.go.kr/genre/education.do"
    }, {
      code: 15,
      areaName: "서초구",
      areaHomepage: "http://www.seocho.go.kr/site/seocho/cultureCitySeocho.do"
    }, {
      code: 16,
      areaName: "성동구",
      areaHomepage: "http://www.sd.go.kr/sd/main.do?op=mainSub&mCode=13C060010011"
    }, {
      code: 17,
      areaName: "성북구",
      areaHomepage: "http://www.sb.go.kr/tour/mainPage.do"
    }, {
      code: 18,
      areaName: "송파구",
      areaHomepage: "http://culture.songpa.go.kr/user.kdf?a=songpa.menu.MenuApp&c=1001&cate_id=AM0000000000"
    }, {
      code: 19,
      areaName: "양천구",
      areaHomepage: "http://www.yangcheon.go.kr/site/yangcheon/ex/bbs/List.do?cbIdx=354"
    }, {
      code: 20,
      areaName: "영등포구",
      areaHomepage: "https://www.ydp.go.kr/tour/index.do"
    }, {
      code: 21,
      areaName: "용산구",
      areaHomepage: "http://munha.yongsan.go.kr/"
    }, {
      code: 22,
      areaName: "은평구",
      areaHomepage: "https://www.ep.go.kr/CmsWeb/viewPage.req?idx=PG0000003320"
    }, {
      code: 23,
      areaName: "종로구",
      areaHomepage: "http://tour.jongno.go.kr/tourMain.do"
    }, {
      code: 24,
      areaName: "중구",
      areaHomepage: "http://www.junggu.seoul.kr/tour/"
    }, {
      code: 25,
      areaName: "중랑구",
      areaHomepage: "http://www.jungnang.go.kr/portal/main/contents.do?menuNo=200649"
    }],

    '2': [{
      code: 1,
      areaName: "강화군",
      areaHomepage: "http://www.ganghwa.go.kr/open_content/tour/"
    }, {
      code: 2,
      areaName: "계양구",
      areaHomepage: "http://www.gyeyang.go.kr/open_content/tour/"
    }, {
      code: 3,
      areaName: "미추홀구",
      areaHomepage: "http://namgu.incheon.kr/home/culture/folkculture_programinfo.asp"
    }, {
      code: 4,
      areaName: "남동구",
      areaHomepage: "http://www.namdong.go.kr/main/area/culture/facility.jsp"
    }, {
      code: 5,
      areaName: "동구",
      areaHomepage: "http://www.icdonggu.go.kr/open_content/culture/"
    }, {
      code: 6,
      areaName: "부평구",
      areaHomepage: "http://www.icbp.go.kr/open_content/tour/"
    }, {
      code: 7,
      areaName: "서구",
      areaHomepage: "http://www.seo.incheon.kr/icarusx/"
    }, {
      code: 8,
      areaName: "연수구",
      areaHomepage: "http://www.yeonsu.go.kr/tour/"
    }, {
      code: 9,
      areaName: "옹진군",
      areaHomepage: "http://www.ongjin.go.kr/tour/"
    }, {
      code: 10,
      areaName: "중구",
      areaHomepage: "http://www.icjg.go.kr/tour/"
    }],

    '3': [{
      code: 1,
      areaName: "대덕구",
      areaHomepage: "http://www.daedeok.go.kr/ect/ECT.do"
    }, {
      code: 2,
      areaName: "동구",
      areaHomepage: "http://tour.donggu.go.kr/"
    }, {
      code: 3,
      areaName: "서구",
      areaHomepage: "http://www.seogu.go.kr/tour/main.do"
    }, {
      code: 4,
      areaName: "유성구",
      areaHomepage: "http://tour.yuseong.go.kr/index.yuseong"
    }, {
      code: 5,
      areaName: "중구",
      areaHomepage: "http://tour.djjunggu.go.kr/html/tour/"
    }],

    '4': [{
      code: 1,
      areaName: "남구",
      areaHomepage: "http://www.nam.daegu.kr/tour/index.do"
    }, {
      code: 2,
      areaName: "달서구",
      areaHomepage: "http://www.dalseo.daegu.kr/tour/index.do"
    }, {
      code: 3,
      areaName: "달성군",
      areaHomepage: "http://culture.dalseong.daegu.kr/"
    }, {
      code: 4,
      areaName: "동구",
      areaHomepage: "http://www.dong.daegu.kr/main/page.htm?mnu_uid=52"
    }, {
      code: 5,
      areaName: "북구",
      areaHomepage: "http://www.buk.daegu.kr/tour"
    }, {
      code: 6,
      areaName: "서구",
      areaHomepage: "http://www.dgs.go.kr/tour/"
    }, {
      code: 7,
      areaName: "수성구",
      areaHomepage: "http://www.suseong.kr/tour"
    }, {
      code: 8,
      areaName: "중구",
      areaHomepage: "http://gu.jung.daegu.kr/new/culture/pages/main/"
    }],

    '5': [{
      code: 1,
      areaName: "광산구",
      areaHomepage: "http://culture.gwangsan.go.kr/"
    }, {
      code: 2,
      areaName: "남구",
      areaHomepage: "http://namgu.gwangju.kr/culture/"
    }, {
      code: 3,
      areaName: "동구",
      areaHomepage: "http://www.donggu.kr/index.es?sid=a9"
    }, {
      code: 4,
      areaName: "북구",
      areaHomepage: "http://culture.bukgu.gwangju.kr/"
    }, {
      code: 5,
      areaName: "서구",
      areaHomepage: "http://culture.seogu.gwangju.kr/index.9is"
    }],

    '6': [{
      code: 1,
      areaName: "강서구",
      areaHomepage: "http://www.bsgangseo.go.kr/visit/main.do"
    }, {
      code: 2,
      areaName: "금정구",
      areaHomepage: "http://tour.geumjeong.go.kr/"
    }, {
      code: 3,
      areaName: "기장군",
      areaHomepage: "http://www.gijang.go.kr/tour/index.gijang"
    }, {
      code: 4,
      areaName: "남구",
      areaHomepage: "http://tour.bsnamgu.go.kr/"
    }, {
      code: 5,
      areaName: "동구",
      areaHomepage: "http://tour.bsdonggu.go.kr/"
    }, {
      code: 6,
      areaName: "동래구",
      areaHomepage: "http://tour.dongnae.go.kr/"
    }, {
      areaName: "부산진구",
      areaHomepage: "http://tour.busanjin.go.kr/"
    }, {
      code: 7,
      areaName: "북구",
      areaHomepage: "http://www.bsbukgu.go.kr/index.do?menuCd=DOM_000000107000000000"
    }, {
      code: 8,
      areaName: "사상구",
      areaHomepage: "http://www.sasang.go.kr/tour/index.sasang"
    }, {
      code: 9,
      areaName: "사하구",
      areaHomepage: "http://tour.saha.go.kr/"
    }, {
      code: 10,
      areaName: "서구",
      areaHomepage: "http://culture.bsseogu.go.kr/"
    }, {
      code: 11,
      areaName: "수영구",
      areaHomepage: "http://www.suyeong.go.kr/tour/"
    }, {
      code: 12,
      areaName: "연제구",
      areaHomepage: "http://culture.yeonje.go.kr"
    }, {
      code: 13,
      areaName: "영도구",
      areaHomepage: "http://tour.yeongdo.go.kr/"
    }, {
      code: 14,
      areaName: "중구",
      areaHomepage: "http://www.bsjunggu.go.kr/tour/index.junggu"
    }, {
      code: 15,
      areaName: "해운대구",
      areaHomepage: "http://www.haeundae.go.kr/tour/index.do"
    }],

    '7': [{
      code: 1,
      areaName: "중구",
      areaHomepage: "http://www.junggu.ulsan.kr/tour/"
    }, {
      code: 2,
      areaName: "남구",
      areaHomepage: "http://www.ulsannamgu.go.kr/tour/main.do"
    }, {
      code: 3,
      areaName: "동구",
      areaHomepage: "http://www.donggu.ulsan.kr/tour/cmm/main/mainPage.do"
    }, {
      code: 4,
      areaName: "북구",
      areaHomepage: "http://www.bukgu.ulsan.kr/lay1/S1T203C306/contents.do"
    }],

    '8': [{
      code: 1,
      areaName: "세종시",
      areaHomepage: "http://www.sejong.go.kr/tour.do"
    }],

    '31': [{
      code: 1,
      areaName: "가평군",
      areaHomepage: "http://www.gptour.go.kr/"
    }, {
      code: 2,
      areaName: "고양시",
      areaHomepage: "http://www.goyang.go.kr/visitgoyang/index.asp"
    }, {
      code: 3,
      areaName: "과천시",
      areaHomepage: "http://www.gccity.go.kr/tour/main.do"
    }, {
      code: 4,
      areaName: "광명시",
      areaHomepage: "http://www.gm.go.kr/tr/index.do"
    }, {
      code: 5,
      areaName: "광주시",
      areaHomepage: "https://www.gjcity.go.kr/tour/main.do"
    }, {
      code: 6,
      areaName: "구리시",
      areaHomepage: "http://www.guri.go.kr/main/cul"
    }, {
      code: 7,
      areaName: "군포시",
      areaHomepage: "http://www.gunpo.go.kr/tour/index.do"
    }, {
      code: 8,
      areaName: "김포시",
      areaHomepage: "https://www.gimpo.go.kr/culture/index.do"
    }, {
      code: 9,
      areaName: "남양주시",
      areaHomepage: "https://www.nyj.go.kr/culture/223"
    }, {
      code: 10,
      areaName: "동두천시",
      areaHomepage: "https://www.ddc.go.kr/tour/index.do"
    }, {
      code: 11,
      areaName: "부천시",
      areaHomepage: "http://www.bucheon.go.kr/site/homepage/menu/viewMenu?menuid=148006001001001"
    }, {
      code: 12,
      areaName: "성남시",
      areaHomepage: "http://www.seongnam.go.kr/city/1000486/30209/bbsList.do"
    }, {
      code: 13,
      areaName: "수원시",
      areaHomepage: "https://www.suwon.go.kr/web/visitsuwon/index.do"
    }, {
      code: 14,
      areaName: "시흥시",
      areaHomepage: "http://www.siheung.go.kr/culture/"
    }, {
      code: 15,
      areaName: "안산시",
      areaHomepage: "https://tourinfo.ansan.go.kr/main.do"
    }, {
      code: 16,
      areaName: "안성시",
      areaHomepage: "https://www.anseong.go.kr/tour/main.do"
    }, {
      code: 17,
      areaName: "안양시",
      areaHomepage: "https://www.anyang.go.kr/main/contents.do?key=1478"
    }, {
      code: 18,
      areaName: "양주시",
      areaHomepage: "https://www.yangju.go.kr/tour/index.do"
    }, {
      code: 19,
      areaName: "양평군",
      areaHomepage: "http://tour.yp21.net/"
    }, {
      code: 20,
      areaName: "여주시",
      areaHomepage: "http://www.yj21.net/kor/culture/index.jsp"
    }, {
      code: 21,
      areaName: "연천군",
      areaHomepage: "http://tour.yeoncheon.go.kr"
    }, {
      code: 22,
      areaName: "오산시",
      areaHomepage: "http://www.osan.go.kr/osanCulture/main.do"
    }, {
      code: 23,
      areaName: "용인시",
      areaHomepage: "https://www.yongin.go.kr/tour/index.do"
    }, {
      code: 24,
      areaName: "의왕시",
      areaHomepage: "http://www.uiwang.go.kr/culture/index"
    }, {
      code: 25,
      areaName: "의정부시",
      areaHomepage: "https://www.ui4u.go.kr/tour/main.do"
    }, {
      code: 26,
      areaName: "이천시",
      areaHomepage: "http://tour.icheon.go.kr/site/tour/main.do"
    }, {
      code: 27,
      areaName: "파주시",
      areaHomepage: "https://tour.paju.go.kr"
    }, {
      code: 28,
      areaName: "평택시",
      areaHomepage: "http://www.pyeongtaek.go.kr/tour/main.do"
    }, {
      code: 29,
      areaName: "포천시",
      areaHomepage: "https://www.pocheon.go.kr/ktour/index.do"
    }, {
      code: 30,
      areaName: "하남시",
      areaHomepage: "http://www.hanam.go.kr/www/contents.do?key=182"
    }, {
      code: 31,
      areaName: "화성시",
      areaHomepage: "http://tour.hscity.go.kr/NEW/0index/index.jsp"
    }],

    '32': [{
      code: 1,
      areaName: "강릉시",
      areaHomepage: "http://www.gntour.go.kr/"
    }, {
      code: 2,
      areaName: "고성군",
      areaHomepage: "http://www.gwgs.go.kr/tour/index.do"
    }, {
      code: 3,
      areaName: "동해시",
      areaHomepage: "https://www.dh.go.kr/tour/"
    }, {
      code: 4,
      areaName: "삼척시",
      areaHomepage: "http://tour.samcheok.go.kr/"
    }, {
      code: 5,
      areaName: "속초시",
      areaHomepage: "http://sokchotour.com/"
    }, {
      code: 6,
      areaName: "양구군",
      areaHomepage: "http://ygtour.kr/"
    }, {
      code: 7,
      areaName: "양양군",
      areaHomepage: "https://tour.yangyang.go.kr"
    }, {
      code: 8,
      areaName: "영월군",
      areaHomepage: "https://www.yw.go.kr/tour/index.do"
    }, {
      code: 9,
      areaName: "원주시",
      areaHomepage: "http://tourism.wonju.go.kr/"
    }, {
      code: 10,
      areaName: "인제군",
      areaHomepage: "http://tour.inje.go.kr/main/main.asp"
    }, {
      code: 11,
      areaName: "정선군",
      areaHomepage: "http://www.jeongseon.go.kr/tour/jeongseontour/attractions"
    }, {
      code: 12,
      areaName: "철원군",
      areaHomepage: "http://tour.cwg.go.kr/site/tour/main.do"
    }, {
      code: 13,
      areaName: "춘천시",
      areaHomepage: "http://tour.chuncheon.go.kr"
    }, {
      code: 14,
      areaName: "태백시",
      areaHomepage: "http://tour.taebaek.go.kr/"
    }, {
      code: 15,
      areaName: "평창군",
      areaHomepage: "http://tour.pc.go.kr/"
    }, {
      code: 16,
      areaName: "홍천군",
      areaHomepage: "http://www.great.go.kr/"
    }, {
      code: 17,
      areaName: "화천군",
      areaHomepage: "http://tour.ihc.go.kr/"
    }, {
      code: 18,
      areaName: "횡성군",
      areaHomepage: "http://tour.hsg.go.kr/tour/"
    }],

    '33': [{
      code: 1,
      areaName: "괴산군",
      areaHomepage: "https://www.goesan.go.kr/tour/index.do"
    }, {
      code: 2,
      areaName: "단양군",
      areaHomepage: "http://www.danyang.go.kr/tour"
    }, {
      code: 3,
      areaName: "보은군",
      areaHomepage: "http://www.tourboeun.go.kr/"
    }, {
      code: 4,
      areaName: "영동군",
      areaHomepage: "http://tour.yd21.go.kr/"
    }, {
      code: 5,
      areaName: "옥천군",
      areaHomepage: "https://www.oc.go.kr/tour/index.do"
    }, {
      code: 6,
      areaName: "음성군",
      areaHomepage: "http://tour.es21.go.kr/"
    }, {
      code: 7,
      areaName: "제천시",
      areaHomepage: "http://tour.jecheon.go.kr/ktour/index.do"
    }, {
      code: 8,
      areaName: "진천군",
      areaHomepage: "https://www.jincheon.go.kr/site/tour/main.do"
    }, {
      code: 9,
      areaName: "청주시",
      areaHomepage: "http://www.cheongju.go.kr/tour/index.do"
    }, {
      code: 10,
      areaName: "충주시",
      areaHomepage: "https://www.chungju.go.kr/tour/index.do"
    }, {
      code: 11,
      areaName: "증평군",
      areaHomepage: "http://tour.jp.go.kr/html/kr/"
    }],

    '34': [{
      code: 1,
      areaName: "공주시",
      areaHomepage: "https://tour.gongju.go.kr"
    }, {
      code: 2,
      areaName: "금산군",
      areaHomepage: "http://www.geumsan.go.kr/tour/"
    }, {
      code: 3,
      areaName: "논산시",
      areaHomepage: "https://www.nonsan.go.kr/tour/"
    }, {
      code: 4,
      areaName: "당진시",
      areaHomepage: "http://www.dangjin.go.kr/html/tour/"
    }, {
      code: 5,
      areaName: "보령시",
      areaHomepage: "http://brcn.go.kr/tour.do"
    }, {
      code: 6,
      areaName: "부여군",
      areaHomepage: "http://tour.buyeo.go.kr/html/tour/"
    }, {
      code: 7,
      areaName: "서산시",
      areaHomepage: "http://www.seosan.go.kr/tour/index.do"
    }, {
      code: 8,
      areaName: "서천군",
      areaHomepage: "http://tour.seocheon.go.kr/"
    }, {
      code: 9,
      areaName: "아산시",
      areaHomepage: "https://www.asan.go.kr/tour/main/"
    }, {
      code: 10,
      areaName: "예산군",
      areaHomepage: "http://www.yesan.go.kr/tour/index.do"
    }, {
      code: 11,
      areaName: "천안시",
      areaHomepage: "https://www.cheonan.go.kr/tour.do"
    }, {
      code: 12,
      areaName: "청양군",
      areaHomepage: "http://tour.cheongyang.go.kr/"
    }, {
      code: 13,
      areaName: "태안군",
      areaHomepage: "http://www.taean.go.kr/tour.do"
    }, {
      code: 14,
      areaName: "홍성군",
      areaHomepage: "http://tour.hongseong.go.kr/"
    }, {
      code: 15,
      areaName: "계룡시",
      areaHomepage: "http://tour.gyeryong.go.kr/html/tour/index.html"
    }],

    '35': [{
      code: 1,
      areaName: "경산시",
      areaHomepage: "http://gbgs.go.kr/tour/"
    }, {
      code: 2,
      areaName: "경주시",
      areaHomepage: "http://guide.gyeongju.go.kr/"
    }, {
      code: 3,
      areaName: "고령군",
      areaHomepage: "http://tour.goryeong.go.kr/"
    }, {
      code: 4,
      areaName: "구미시",
      areaHomepage: "http://www.gumi.go.kr/tour/main.do"
    }, {
      code: 5,
      areaName: "군위군",
      areaHomepage: "http://www.gunwi.go.kr/tour/main.htm"
    }, {
      code: 6,
      areaName: "김천시",
      areaHomepage: "http://www.gc.go.kr/culture/"
    }, {
      code: 7,
      areaName: "문경시",
      areaHomepage: "https://www.gbmg.go.kr/tour/main.do"
    }, {
      code: 8,
      areaName: "봉화군",
      areaHomepage: "https://www.bonghwa.go.kr/open.content/tour/"
    }, {
      code: 9,
      areaName: "상주시",
      areaHomepage: "https://www.sangju.go.kr/tour/"
    }, {
      code: 10,
      areaName: "성주군",
      areaHomepage: "http://www.sj.go.kr/tour/"
    }, {
      code: 11,
      areaName: "안동시",
      areaHomepage: "http://www.tourandong.com/"
    }, {
      code: 12,
      areaName: "영덕군",
      areaHomepage: "http://tour.yd.go.kr/"
    }, {
      code: 13,
      areaName: "영양군",
      areaHomepage: "https://www.yyg.go.kr/tour"
    }, {
      code: 14,
      areaName: "영주시",
      areaHomepage: "http://www.yeongju.go.kr/open_content/tour/index.do"
    }, {
      code: 15,
      areaName: "영천시",
      areaHomepage: "https://www.yc.go.kr/tour"
    }, {
      code: 16,
      areaName: "예천군",
      areaHomepage: "http://tour.ycg.kr/open.content/ko"
    }, {
      code: 17,
      areaName: "울릉군",
      areaHomepage: "http://www.ulleung.go.kr/tour/"
    }, {
      code: 18,
      areaName: "울진군",
      areaHomepage: "https://www.uljin.go.kr/tour/index.uljin"
    }, {
      code: 19,
      areaName: "의성군",
      areaHomepage: "https://www.usc.go.kr/tour/main.tc"
    }, {
      code: 20,
      areaName: "청도군",
      areaHomepage: "http://www.cheongdo.go.kr/open.content/tour/"
    }, {
      code: 21,
      areaName: "청송군",
      areaHomepage: "http://www.cs.go.kr/tour.web"
    }, {
      code: 22,
      areaName: "칠곡군",
      areaHomepage: "http://tour.chilgok.go.kr/main/"
    }, {
      code: 23,
      areaName: "포항시",
      areaHomepage: "http://phtour.ipohang.org/"
    }],

    '36': [{
      code: 1,
      areaName: "거제시",
      areaHomepage: "http://tour.geoje.go.kr/"
    }, {
      code: 2,
      areaName: "거창군",
      areaHomepage: "https://www.geochang.go.kr/tour/Index.do"
    }, {
      code: 3,
      areaName: "고성군",
      areaHomepage: "http://visit.goseong.go.kr/"
    }, {
      code: 4,
      areaName: "김해시",
      areaHomepage: "http://tour.gimhae.go.kr/"
    }, {
      code: 5,
      areaName: "남해군",
      areaHomepage: "http://tour.namhae.go.kr/main.web"
    }, {
      code: 6,
      areaName: "밀양시",
      areaHomepage: "http://tour.miryang.go.kr/main/"
    }, {
      code: 7,
      areaName: "사천시",
      areaHomepage: "http://www.toursacheon.net/"
    }, {
      code: 8,
      areaName: "산청군",
      areaHomepage: "http://www.sancheong.go.kr/tour/index.do"
    }, {
      code: 9,
      areaName: "양산시",
      areaHomepage: "http://www.yangsan.go.kr/tour/main.do"
    }, {
      code: 10,
      areaName: "의령군",
      areaHomepage: "http://tour.uiryeong.go.kr/"
    }, {
      code: 11,
      areaName: "진주시",
      areaHomepage: "http://www.jinju.go.kr/tour.web"
    }, {
      code: 12,
      areaName: "창녕군",
      areaHomepage: "http://tour.cng.go.kr/main/"
    }, {
      code: 13,
      areaName: "창원시",
      areaHomepage: "http://culture.changwon.go.kr/index.changwon?contentId=9"
    }, {
      code: 14,
      areaName: "통영시",
      areaHomepage: "http://www.utour.go.kr/main/"
    }, {
      code: 15,
      areaName: "하동군",
      areaHomepage: "http://tour.hadong.go.kr/"
    }, {
      code: 16,
      areaName: "함안군",
      areaHomepage: "http://www.haman.go.kr/tour.web"
    }, {
      code: 17,
      areaName: "함양군",
      areaHomepage: "http://www.hygn.go.kr/tour.web"
    }, {
      code: 18,
      areaName: "합천군",
      areaHomepage: "http://www.hc.go.kr/tour.web"
    }],

    '37': [{
      code: 1,
      areaName: "고창군",
      areaHomepage: "https://www.gochang.go.kr/culture/index.gochang"
    }, {
      code: 2,
      areaName: "군산시",
      areaHomepage: "http://www.gunsan.go.kr/tour/index.gunsan"
    }, {
      code: 3,
      areaName: "김제시",
      areaHomepage: "http://www.gimje.go.kr/index.gimje?tab=03"
    }, {
      code: 4,
      areaName: "남원시",
      areaHomepage: "https://www.namwon.go.kr/tour/index.do"
    }, {
      code: 5,
      areaName: "무주군",
      areaHomepage: "http://tour.muju.go.kr"
    }, {
      code: 6,
      areaName: "부안군",
      areaHomepage: "http://www.buan.go.kr/tour/index.buan"
    }, {
      code: 7,
      areaName: "순창군",
      areaHomepage: "http://www.sunchang.go.kr/tour/index.sunchang"
    }, {
      code: 8,
      areaName: "완주군",
      areaHomepage: "http://tour.wanju.go.kr/"
    }, {
      code: 9,
      areaName: "익산시",
      areaHomepage: "http://www.iksan.go.kr/tour/"
    }, {
      code: 10,
      areaName: "임실군",
      areaHomepage: "http://tour.imsil.go.kr/"
    }, {
      code: 11,
      areaName: "장수군",
      areaHomepage: "http://www.jangsu.go.kr/tour/index.jangsu"
    }, {
      code: 12,
      areaName: "전주시",
      areaHomepage: "http://tour.jeonju.go.kr/index.9is"
    }, {
      code: 13,
      areaName: "정읍시",
      areaHomepage: "http://culture.jeongeup.go.kr/"
    }, {
      code: 14,
      areaName: "진안군",
      areaHomepage: "https://tour.jinan.go.kr/"
    }],

    '38': [{
      code: 1,
      areaName: "강진군",
      areaHomepage: "http://www.gangjin.go.kr/culture/index.do"
    }, {
      code: 2,
      areaName: "고흥군",
      areaHomepage: "http://www.goheung.go.kr/tour/"
    }, {
      code: 3,
      areaName: "곡성군",
      areaHomepage: "http://www.gokseong.go.kr/tour/"
    }, {
      code: 4,
      areaName: "광양시",
      areaHomepage: "https://www.gwangyang.go.kr/tour_culture/index.gwangyang"
    }, {
      code: 5,
      areaName: "구례군",
      areaHomepage: "http://tour.gurye.go.kr/jcms/guryetours/"
    }, {
      code: 6,
      areaName: "나주시",
      areaHomepage: "http://tour.naju.go.kr/"
    }, {
      code: 7,
      areaName: "담양군",
      areaHomepage: "http://tour.damyang.go.kr/index.damyang"
    }, {
      code: 8,
      areaName: "목포시",
      areaHomepage: "http://www.mokpo.go.kr/tour"
    }, {
      code: 9,
      areaName: "무안군",
      areaHomepage: "http://tour.muan.go.kr/"
    }, {
      code: 10,
      areaName: "보성군",
      areaHomepage: "http://tour.boseong.go.kr"
    }, {
      code: 11,
      areaName: "순천시",
      areaHomepage: "https://www.suncheon.go.kr/tour/"
    }, {
      code: 12,
      areaName: "신안군",
      areaHomepage: "http://tour.shinan.go.kr/"
    }, {
      code: 13,
      areaName: "여수시",
      areaHomepage: "http://tour.yeosu.go.kr/"
    }, {
      code: 14,
      areaName: "영광군",
      areaHomepage: "http://tour.yeonggwang.go.kr/"
    }, {
      code: 15,
      areaName: "영암군",
      areaHomepage: "http://www.yeongam.go.kr/home/tour"
    }, {
      code: 16,
      areaName: "완도군",
      areaHomepage: "http://www.wando.go.kr/tour/"
    }, {
      code: 17,
      areaName: "장성군",
      areaHomepage: "http://tour.jangseong.go.kr/"
    }, {
      code: 18,
      areaName: "장흥군",
      areaHomepage: "http://www.jangheung.go.kr/tour"
    }, {
      code: 19,
      areaName: "진도군",
      areaHomepage: "http://tour.jindo.go.kr/"
    }, {
      code: 20,
      areaName: "함평군",
      areaHomepage: "https://www.hampyeong.go.kr/tour/"
    }, {
      code: 21,
      areaName: "해남군",
      areaHomepage: "http://tour.haenam.go.kr/"
    }, {
      code: 22,
      areaName: "화순군",
      areaHomepage: "http://www.hwasun.go.kr/index.do?S=S09"
    }],

    '39': [{
        code: 1,
        areaName: "서귀포시",
        areaHomepage: "https://www.seogwipo.go.kr/field/tourist.htm"
      }, {
        code: 2,
        areaName: "제주시",
        areaHomepage: "https://www.visitjeju.net"
    }]
}